import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import localFont from "next/font/local";

const beaufort = localFont({ src: "../fonts/BeaufortforLOL-Regular.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={beaufort.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
